image: ruby:2.5.1
pipelines:
  default:
    - step:
        script:
          - ruby -v
          - gem install coffee-rails
          - gem install bundler
          - bundle install
          - bundle exec spring binstub --all
          - rspec
