image: ruby:2.5.1
pipelines:
  default:
    - step:
        script:
          - ruby -v
          - gem install coffee-rails
          - gem install bundler
          - bundle exec spring binstub --all
          - bundle exec rake db:migrate
