image: ruby:2.5.1
pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - ruby -v
          - gem install coffee-rails
          - gem install bundler
          - bundle install --path vendor/bundle
          - bundle exec spring binstub --all
          - rspec
definitions:
  caches:
    bundler: vendor/bundle
