# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71669f187459dd4412b3170e0b4cc56493f60e7c311976125ac809c8354071baa2cf7cf8f2fecffc3bd041956fe71ef2408fb9ebf4d5a7681a04867424327fc1

test:
  secret_key_base: 2b65c0ecbe7a3dbc94b66ef5d8fb2493ae8a7215477e8523bed2f28f885a15576bef21d1b3a6288ef1117dd57f2f1e265fd773f9307e249757402618eaed1011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
